version: '3'

services:
  api:
    build:
      context: ./agents-api
      dockerfile: Containerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agents_ui
      - SECRET_KEY=your_secret_key_change_this_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["http://localhost:5173"]
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./agents-api:/app:Z
    depends_on:
      - db
      - redis
    
  ui:
    build:
      context: ./agents-ui
      dockerfile: Containerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./agents-ui:/app:Z
      - /app/node_modules
    
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agents_ui
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    
  redis:
    image: redis:7
    volumes:
      - redis_data:/data:Z
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: