FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml .
COPY app ./app
COPY alembic.ini .
COPY alembic ./alembic

RUN pip install --no-cache-dir -e .
RUN pip install python-dotenv

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]